// Generated by Apple Swift version 5.3 (swiftlang-1200.0.29.2 clang-1200.0.30.1)
#ifndef AXEDEVTOOLSXCUI_SWIFT_H
#define AXEDEVTOOLSXCUI_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="axeDevToolsXCUI",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif


/// The AccessToken handles logging into the axeDevTools server and keeping the session alive.  Users who have their own instance of the axeDevTools server may need to use this class.  If you are using the default server, you should not need to use this class.
SWIFT_CLASS("_TtC15axeDevToolsXCUI11AccessToken")
@interface AccessToken : NSObject
/// Creates a new AccessToken with the given parameters.
/// This will throw an error if the parameters provided are not correct.
/// note:
/// Google authentication information will not work.
/// \param username Your username used to log into mobile docs and the axeDevTools Dashboard.  Usually an email address.
///
/// \param password The password used to log into mobile docs and the axeDevTools Dashboard.
///
/// \param realm Optional. Provide this if you have your own instance of the axeDevTools server.
///
/// \param clientId Optional. Provide this if you have your own instance of the axeDevTools server.
///
/// \param clientSecret Optional. Provide this if you have your own instance of the axeDevTools server.
///
/// \param authServerURL Optional. Provide this if you have your own instance of the axeDevTools server.
///
- (nullable instancetype)initWithUsername:(NSString * _Nonnull)username password:(NSString * _Nonnull)password realm:(NSString * _Nonnull)realm clientId:(NSString * _Nonnull)clientId clientSecret:(NSString * _Nonnull)clientSecret authServerURL:(NSString * _Nonnull)authServerURL error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class AxeConf;
@class AttestClient;
@class AxeResult;

/// The Attest class contains many static methods for you to set up automated accessibility scanning.
/// This class allows you to
/// <ul>
///   <li>
///     set up and run an accessibility test on an entire screen
///   </li>
///   <li>
///     configure the Floating Action Button
///   </li>
///   <li>
///     adjust which rules you would like to run
///   </li>
///   <li>
///     turn on advanced logging (if you run into an issue, sometimes additional logging can be useful to help us debug!)
///   </li>
/// </ul>
SWIFT_CLASS("_TtC15axeDevToolsXCUI6Attest") SWIFT_DEPRECATED_MSG("This class will be removed November 2022. Please use `AxeDevTools` instead.", "_TtC15axeDevToolsXCUI11AxeDevTools")
@interface Attest : NSObject
/// Set this property if you want to change which rules are run or if you want to add custom rules.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) AxeConf * _Nonnull configuration;)
+ (AxeConf * _Nonnull)configuration SWIFT_WARN_UNUSED_RESULT;
+ (void)setConfiguration:(AxeConf * _Nonnull)value;
/// Set this property to <code>true</code> if you want additional debug information for unexpected behavior.
/// We may request this to be turned on if an obscure bug is found.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) BOOL debugStatements;)
+ (BOOL)debugStatements SWIFT_WARN_UNUSED_RESULT;
+ (void)setDebugStatements:(BOOL)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) BOOL logWarnings SWIFT_DEPRECATED_MSG("This method will be removed November 2022. Please use `debugStatements` instead.");)
+ (BOOL)logWarnings SWIFT_WARN_UNUSED_RESULT;
+ (void)setLogWarnings:(BOOL)value;
/// Sets up a local connection with the Attest Desktop Application.  This is required to locally push results
/// and use manual testing with the Desktop Application.
/// \param port the port number of the local server running in the Attest Desktop Application.
/// If not specified, the port defaults to 48485.
///
+ (void)setLocalConnectionWithPort:(NSUInteger)port;
/// Use this function to log into the cloud instance of the Attest Service.  This can be used in the
/// AppDelegate/SceneDelegate (for manual or UI Testing) before attaching the FAB to the application,
/// or it can be used to push results to the Attest Service in Unit Tests.
/// If you are using Objective-C, simply pass in an empty String to the <code>url</code> parameter, and the Attest
/// class will set the URL to the default server.  If you do not provide the correct credentials, an error
/// message (with <code>DEQUE</code>) will be printed to the console, and no results will be pushed to the cloud
/// server. Do NOT use this method to connect to the Desktop Client, as it will not work.  Please instead
/// use <code>setLocalConnection</code>.
/// note:
/// Google authentication information does not work in this method.
/// \param url the URL of the server you want to send scans to, as a String.  Defaults to the default cloud instance of the server.  Most users should not need to change this from default.
///
/// \param username your username for the Attest Service, as a String. Usually is an email address.
///
/// \param password your password for the Attest Service, as a String.
///
+ (void)setServerTo:(NSString * _Nonnull)url withUsername:(NSString * _Nonnull)username andPassword:(NSString * _Nonnull)password SWIFT_DEPRECATED_MSG("This method will be removed November 2022. Please use `login` within AxeDevTools class instead.");
/// Use this method to log into the cloud instance of the Attest Service.  Recommended for use in UI
/// Integrated Tests. Having access to the AttestClient directly gives you additional access to API such
/// as being able to retrieve, tag, and delete scans from the server.
/// \param attestClient a class that allows you to directly interact with the Attest server.
/// See <code>AttestClient</code> for more information.
///
+ (void)setServerUsingAttestClient:(AttestClient * _Nonnull)attestClient SWIFT_DEPRECATED_MSG("This method will be removed November 2022. Please use `login` within AxeDevTools class instead.");
/// Returns an initialized Attest object. Can be used in your UI Tests to test a screen written in Swift UI.
/// \param element The root element of the screen you wanted tested, or one component.  Must be an XCUIElement.
///
///
/// returns:
/// Initialized Attest object.
+ (Attest * _Nullable)thatWithElement:(id _Nonnull)element SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_MSG("This method will be removed November 2022. Please use `run` within `AxeDevTools` instead.");
/// Use this in a Unit Test to analyze the accessibility of the view or View Controller specified in the Attest class.
///
/// returns:
/// the result of the scan, as an AxeResult.
- (AxeResult * _Nonnull)isAccessible SWIFT_DEPRECATED_MSG("This method will be removed November 2022. Please use `run` within `AxeDevTools` instead.");
/// Removes Rules from the Ruleset.  Attest will <em>not</em> use the Rules specified when running a scan.
/// This can be used in Unit Tests.
/// \param rules A list of Rules that should <em>not</em> be run in Attest, as an array of String.
///
///
/// returns:
/// An initialized Attest class.
- (Attest * _Nonnull)butNotWithRules:(NSArray<NSString *> * _Nonnull)rules SWIFT_DEPRECATED_MSG("This method will be removed November 2022.  Please use the `configuration` variable within `AxeDevTools` to update rules instead.");
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class AttestResultKey;

/// AttestClient allows you to log into and interact with the Attest server.  With the AttestClient, you can directly
/// push up scans to the server, and also retrieve, tag, and delete scans available on the server.
/// We recommend using this API in conjunction with UI Tests. This way, you can automate pressing the Floating
/// Action Button on every scan, and then retrieve the scan from the server so that the UI Tests can assert
/// whatever information you want about the scan (if there are failures, if the failures are only from one
/// rule, how many passes there are, etc).
SWIFT_CLASS("_TtC15axeDevToolsXCUI12AttestClient") SWIFT_DEPRECATED_MSG("This class will be removed November 2022. Please use `AxeDevTools`.")
@interface AttestClient : NSObject
/// Use this to log into the cloud instance of the Attest Service.  This will return <code>nil</code> and print to the console if the framework could not connect to the Attest Service.  If you are running into login issues, please search the console for <code>DEQUE</code> messages.
/// \param username The username you use to log into the Attest Service.  This may be your email address.
///
/// \param password The password you use to log into the Attest Service.
///
/// \param serverURL The location of the cloud server. It defaults to the default cloud instance of the server.
///
- (nullable instancetype)initWithUsername:(NSString * _Nonnull)username password:(NSString * _Nonnull)password serverURL:(NSString * _Nonnull)serverURL;
- (nullable instancetype)initWithAccessToken:(AccessToken * _Nonnull)accessToken serverURL:(NSString * _Nonnull)serverURL;
/// Use this to log into a local instance of the Attest Service (Desktop Client).  This will return <code>nil</code> and print to the console if the framework could not find the server instance.  The Desktop Client must be open and running for this call to work correctly.  Search the console for <code>DEQUE</code> messages if there are login issues.
/// \param port The port number on which the local Attest Service is hosted. Default is 48485.
///
- (nullable instancetype)initWithPort:(NSUInteger)port OBJC_DESIGNATED_INITIALIZER;
/// This retrieves the AxeResult from the Results server.
/// You may want to do this if your UI Tests just pushed a result to the server by pressing the purple
/// Floating Action Button. The Floating Action Button will contain an AttestResultKey that you can then use
/// to assert things about the scan – such as, if there were any inaccessible views, or whether there were
/// only failures from one rule.
/// \param resultKey The AttestResultKey of the AxeResult you would like to retrieve from the server.
///
///
/// returns:
/// The scan from the Server, as <code>Data</code>. Use <code>JSONDecoder().decode()</code> to convert <code>Data</code> to the
/// <code>AxeResult</code>. This will return <code>nil</code> if there was an issue with retrieving the scan from the server.
/// Please see the Console for more information about the error.
- (NSData * _Nullable)getResult:(AttestResultKey * _Nonnull)resultKey SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_MSG("This method has been moved to AxeDevTools.");
/// This tags the scan with the corresponding AttestResultKey.
/// \param resultKey The AttestResultKey of the scan you would like to tag.
///
/// \param tags The tags you would like to give the scan, as <code>[String]</code>.
///
///
/// returns:
/// the AttestResultKey of the scan you tagged. This will return <code>nil</code> if there was an error with
/// tagging a scan. If it returns <code>nil</code>, please see the Console for more information about the error.
- (AttestResultKey * _Nullable)tagResult:(AttestResultKey * _Nonnull)resultKey tags:(NSArray<NSString *> * _Nonnull)tags SWIFT_DEPRECATED_MSG("This method has been moved to AxeDevTools.");
/// Add the ability to set/update the scan name that is displayed in the dashboard.
/// \param resultKey The AttestResultKey of the scan you would like to update.
///
/// \param name The name to update the scan to.
///
- (void)updateScanName:(AttestResultKey * _Nonnull)resultKey name:(NSString * _Nullable)name SWIFT_DEPRECATED_MSG("This method has been moved to AxeDevTools.");
/// Deletes the result if the result exists in the server.
/// \param resultKey the AttestResultKey of the scan that should be deleted from the server.
///
///
/// returns:
/// Bool, indicating whether the scan was successfully deleted from the server.
- (BOOL)deleteResult:(AttestResultKey * _Nonnull)resultKey SWIFT_DEPRECATED_MSG("This method has been moved to AxeDevTools.");
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// A scan’s unique identifier on the Results server. You can use the AttestResultKey to retrieve, tag, and
/// delete scans on the server.
SWIFT_CLASS("_TtC15axeDevToolsXCUI15AttestResultKey") SWIFT_DEPRECATED_MSG("This class has been renamed and will be removed November 2022. Please use `AxeDevToolsResultKey` instead.", "_TtC15axeDevToolsXCUI20AxeDevToolsResultKey")
@interface AttestResultKey : NSObject
/// The name of the application that the scan came from. Should be the Bundle Identifier.
@property (nonatomic, readonly, copy) NSString * _Nonnull packageName;
/// A unique String associated with the user who pushed up the scan.
@property (nonatomic, readonly, copy) NSString * _Nonnull userId;
/// A unique String associated with the specific scan.
@property (nonatomic, readonly, copy) NSString * _Nonnull resultId;
@property (nonatomic, readonly) NSUInteger hash;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
/// Use this in UI Testing to convert the Floating Action Button title into a valid AttestResultKey.
/// This can then be used for functionality available in <code>AttestClient</code>. This will return <code>nil</code> if there
/// was an error with pushing the scan to the results server.
/// \param fabTitle The <code>title</code> of the Floating Action Button after the UI Test automatically presses
/// it, sending a scan to the Results server.
///
- (nullable instancetype)initWithFabTitle:(NSString * _Nonnull)fabTitle OBJC_DESIGNATED_INITIALIZER;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// A class that contains the location and dimensions of a rectangle, in iOS points.
SWIFT_CLASS("_TtC15axeDevToolsXCUI7AxeRect")
@interface AxeRect : NSObject
/// The left-most bounds of the frame, in pts. Equal to CGRect <code>minX</code> property.
@property (nonatomic, readonly) float left;
/// The right-most bounds of the frame, in pts.
@property (nonatomic, readonly) float right;
/// The top-most bounds of the frame, in pts. Equal to CGRect <code>minY</code> property.
@property (nonatomic, readonly) float top;
/// The bottom-most bounds of the frame, in pts.
@property (nonatomic, readonly) float bottom;
/// The height of the frame, in pts.  Equal to <code>bottom - top</code>.
@property (nonatomic, readonly) float height;
/// The width of the frame, in pts.  Equal to <code>right - left</code>.
@property (nonatomic, readonly) float width;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@property (nonatomic, readonly) NSUInteger hash;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// A class that contains the location and dimensions of a rectangle, in on-screen pixels.
SWIFT_CLASS("_TtC15axeDevToolsXCUI9AxeBounds")
@interface AxeBounds : AxeRect
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end


/// The configuration for an axeDevTools object.
/// By default, all <code>AxeRule</code>s will run. You can use this object to ignore rules, or add custom rules that you define.
SWIFT_CLASS("_TtC15axeDevToolsXCUI7AxeConf")
@interface AxeConf : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
/// Creates a new <code>AxeConf</code> object.  All rules are added by default.  See <code>AxeRuleId</code> for a full list of available rules.
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
/// This method allows you to ignore (or re-introduce) results from any rule, including custom rules.  By default, no rules (including custom rules) are ignored.
/// \param rule the rule’s <code>AxeRuleId</code> (or a custom rule’s class name) whose results should be ignored (or included), as a String.
///
/// \param shouldIgnore a <code>Bool</code> indicating whether the rule’s results should be ignored. Set to <code>true</code> if the rule’s results should be ignored, or <code>false</code> if the rule’s results should be included.  Default value is <code>true</code>.
///
- (void)ignoreWithRule:(NSString * _Nonnull)rule :(BOOL)shouldIgnore;
/// This method allows you to ignore (or re-introduce) results from any rule, including custom rules.  By default, no rules (including custom rules) are ignored.
/// \param rules the <code>AxeRuleId</code>s (or classNames, for custom rules) of the rules you wish to ignore, as a <code>String</code>.
///
/// \param shouldIgnore a <code>Bool</code> indicating whether the set of rules should have their results ignored. Set to <code>true</code> if they should be ignored or <code>false</code> if they should be included.  Default value is <code>true</code>.
///
- (void)ignoreWithRules:(NSArray<NSString *> * _Nonnull)rules :(BOOL)shouldIgnore;
/// Ignore specific rules for specific views, as defined in the provided dictionary, by Class or Accessibility Identifier.
/// Classes that inherit from a classname specified here will not be ignored.  For example, if you specify that the rule <code>InScrollView</code> should not run on any <code>UILabel</code>, <code>InScrollView</code> will still run on the class <code>DQLabel</code> (which inherits from <code>UILabel</code>).
/// *
/// \param rulesFor A dictionary where each key, the Class name or Accessibility Identifier of a view, has a <code>Set</code> of <code>Strings</code> containing Rule Id’s to ignore.
///
- (void)ignoreWithRulesFor:(NSDictionary<NSString *, NSSet<NSString *> *> * _Nonnull)rulesFor;
/// Removes a list of <code>AxeStandard</code>s from the configuration.
/// This can be used to remove a list of rules associated with a standard from being run. For example, if you do not want Best Practice rules to run, you can use this function to remove Best Practice rules from the configuration.
/// \param standards A list of standards that should be removed from the configuration, as an array of <code>String</code>.
///
- (void)removeWithStandards:(NSArray<NSString *> * _Nonnull)standards SWIFT_DEPRECATED_MSG("This method will be removed November 2022. Please use the `ignore` method instead.");
/// Adds a list of <code>AxeRule</code>s to the configuration.
/// This can be used to add a list of rules that you want to run.
/// \param rules A list of rules that should be added to the configuration, as an <code>Array<String></code>.
///
- (void)addWithRules:(NSArray<NSString *> * _Nonnull)rules SWIFT_DEPRECATED_MSG("This method will be removed November 2022. Please use the `ignore(rule)` or `ignore(rules)` functions instead.");
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@end

@class AxeView;
@class AxeDevice;
@class AxeImage;
@class AxeMetaData;

/// Lives within AxeResult and contains meta data about the scan, device information, the screenshot, and the view hierarchy.
SWIFT_CLASS("_TtC15axeDevToolsXCUI10AxeContext")
@interface AxeContext : NSObject
/// The view hierarchy of the scanned view.
@property (nonatomic, readonly, strong) AxeView * _Nonnull axeView;
/// Information about the device used for the scan.
@property (nonatomic, readonly, strong) AxeDevice * _Nonnull axeDevice;
/// A screenshot of the view that was scanned.
@property (nonatomic, readonly, strong) AxeImage * _Nonnull screenshot;
/// Additional meta data.
@property (nonatomic, readonly, strong) AxeMetaData * _Nonnull axeMetaData;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


@class AxeDevToolsResultKey;

/// AxeDevTools class contains many static methods for you to set up testing for accessibility.
/// With this class, you can:
/// <ul>
///   <li>
///     set up an automated accessibility test for either an entire screen or a single view
///   </li>
///   <li>
///     add the floating action button to your application to scan the current screen’s contents for accessibility issues when pressed
///   </li>
///   <li>
///     configure your accessibility tests to suit your needs
///   </li>
/// </ul>
SWIFT_CLASS("_TtC15axeDevToolsXCUI11AxeDevTools")
@interface AxeDevTools : NSObject
/// Set this property if you want to change which rules are run or if you want to add custom rules.
@property (nonatomic, strong) AxeConf * _Nonnull configuration;
/// Set this property to <code>true</code> if you want additional debug information for unexpected behavior.
/// We may request this to be turned on if an obscure bug is found.
@property (nonatomic) BOOL debugStatements;
/// This function logs you into the cloud instance of axeDevTools. You must have a valid session before utilizing the framework’s features. This function can be called in App or Scene Delegate to set up manual tests (to show the Floating Action Button) and also can be used to set up automated tests.
/// warning:
/// To connect to axeDevTools for Desktop: use <code>setLocalConnection</code>.
/// <ul>
///   <li>
///     For Objective-C, pass in an empty String to the <code>url</code> parameter and the default server will be used.
///   </li>
///   <li>
///     Will throw an error if there were incorrect credentials.
///   </li>
///   <li>
///     Google authentication information does not work in this method.
///   </li>
/// </ul>
/// \param username Username for axeDevTools. Usually an email address.
///
/// \param password Password for axeDevTools.
///
/// \param url URL of the server receiving the scans if it’s not Deque’s service. This should only be filled out for enterprises with their own instance.
///
///
/// returns:
/// An instantiated AxeDevTools object.  You will not be able to scan anything without this object.
+ (AxeDevTools * _Nullable)loginWithUsername:(NSString * _Nonnull)username andPassword:(NSString * _Nonnull)password toServer:(NSString * _Nonnull)url error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
/// This function logs you into the cloud instance of axeDevTools. You must have a valid session before utilizing the framework’s features. This function can be called in App or Scene Delegate to set up manual tests (to show the Floating Action Button) and also can be used to set up automated tests.
/// warning:
/// To connect to axeDevTools for Desktop:  use <code>setLocalConnection</code>.
/// <ul>
///   <li>
///     For Objective-C, pass in an empty String to the <code>url</code> parameter and the default server will be used.
///   </li>
///   <li>
///     Will throw an error if there were incorrect credentials.
///   </li>
///   <li>
///     Google authentication information does not work in this method.
///   </li>
/// </ul>
/// \param apiKey API Key for axeDevTools.
///
/// \param url URL of the server receiving the scans if it’s not Deque’s service. This should only be filled out for enterprises with their own instance.
///
///
/// returns:
/// An instantiated AxeDevTools object.  You will not be able to scan anything without this object.
+ (AxeDevTools * _Nullable)loginWithAPIKey:(NSString * _Nonnull)apiKey toServer:(NSString * _Nonnull)url error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
/// This function logs you into the cloud instance of axeDevTools. You must have a valid session before utilizing the framework’s features. This function can be called in App or Scene Delegate to set up manual tests (to show the Floating Action Button) and also can be used to set up automated tests.  Use this version of login if you have a special instance of the server to log into.
/// <ul>
///   <li>
///     Google authentication information does not work in this method.
///   </li>
///   <li>
///     Will throw an error if there were incorrect credentials.
///   </li>
/// </ul>
/// \param accessToken If you require this method, a Deque representative will give you the information needed to create a valid AccessToken.
///
/// \param url URL of the server receiving the scans.  A Deque representative will give you the information needed to fill out this parameter.
///
///
/// returns:
/// initialized AxeDevTools object. Will throw an error if there was an issue logging in.
+ (AxeDevTools * _Nullable)loginWithAccessToken:(AccessToken * _Nonnull)accessToken toServer:(NSString * _Nonnull)url error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
/// Sets up a local connection with the axeDevTools Desktop Client.  This is required to post scans locally and use manual testing with the Desktop Client.
/// warning:
/// The Desktop Client must be open and ready to accept scans before this method is called.  This method may throw an error otherwise.
///
/// returns:
/// initialized AxeDevTools object.
+ (AxeDevTools * _Nullable)setLocalConnectionAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
/// Retrieves the scan from the server.  This can be used within UITests to assert things about a scan that was pushed to the server, such as the number of accessibility issues within a scan.  Will throw an error if there was an issue retrieving the scan.
/// \param resultKey The AxeDevToolsResultKey of the scan you would like to retrieve from the server.
///
///
/// returns:
/// The scan from the server.
- (AxeResult * _Nullable)getResult:(AxeDevToolsResultKey * _Nonnull)resultKey error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
/// Use this after calling <code>run</code> to send the scan to the server.  Will throw an error if sending the scan was not successful.
/// \param result The result that should be pushed to the dashboard.
///
/// \param tags A list of tags that should be associated with the scan, as an array of String.
///
/// \param scanName A String to change the scan name to in the dashboard.
///
///
/// returns:
/// AxeDevToolsResultKey, which can be used to retrieve the scan from the server.
- (AxeDevToolsResultKey * _Nullable)postResult:(AxeResult * _Nonnull)result withTags:(NSArray<NSString *> * _Nonnull)tags withScanName:(NSString * _Nullable)scanName error:(NSError * _Nullable * _Nullable)error;
/// Use this after calling <code>run</code> in your unit test to save the scan to your machine, as JSON.
/// note:
/// This function does not allow you to change the extension of the file; at this point in time it can only be saved as JSON.
/// This function will not overwrite a file if the file already exists.  Instead, it will attach a number to the end of the file name (for example, “appIdentifier-screenTitle-1.json”).
/// \param result The result that should be saved to your machine.
///
/// \param path where you want the scan to be saved to, as a String.  The path will automatically be appended to your home directory.  If not specified, the scan will save into a folder called “AxeDevToolsResults” in your home directory (/Users/yourname/).
///
/// \param name What you want the file to be called, as a String. If not specified, the file’s name will be  “appIdentifier-screenTitle”.
///
///
/// returns:
/// String, the path to the saved file.
- (NSString * _Nullable)saveResult:(AxeResult * _Nonnull)result toPath:(NSString * _Nonnull)path withName:(NSString * _Nonnull)name error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
/// Tags the scan in the dashboard with the strings provided.  Will throw an error if there was an issue tagging the scan.
/// \param resultKey The AxeDevToolsResultKey of the scan you would like to tag.
///
/// \param tags The tags you would like to give the scan, as <code>[String]</code>.
///
- (BOOL)tagResult:(AxeDevToolsResultKey * _Nonnull)resultKey withTags:(NSArray<NSString *> * _Nonnull)tags error:(NSError * _Nullable * _Nullable)error;
/// Deletes the scan from the server.  The scan will no longer be available on the dashboard. Will throw an error if there was an issue deleting the scan.
/// \param resultKey the AxeDevToolsResultKey of the scan that should be deleted from the server.
///
- (BOOL)deleteResult:(AxeDevToolsResultKey * _Nonnull)resultKey error:(NSError * _Nullable * _Nullable)error;
/// Sets or updates the scan name that is displayed in the dashboard. Will throw an error if there was an issue (re)naming the scan.
/// \param resultKey The AxeDevToolsResultKey of the scan you would like to update.
///
/// \param scanName The name you would like to give the scan.
///
- (BOOL)updateScanName:(AxeDevToolsResultKey * _Nonnull)resultKey to:(NSString * _Nonnull)scanName error:(NSError * _Nullable * _Nullable)error;
/// Returns an initialized Attest object. Can be used in your UI Tests to test a screen written in Swift UI.
/// \param element The root element of the screen you wanted tested, or one component.  Must be an XCUIElement.
///
///
/// returns:
/// Initialized Attest object.
- (AxeResult * _Nullable)runOnElement:(id _Nonnull)element error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// A scan’s unique identifier on the axeDevTools Mobile server. You can use the AxeDevToolsResultKey to retrieve, tag, and
/// delete scans on the server.
SWIFT_CLASS("_TtC15axeDevToolsXCUI20AxeDevToolsResultKey")
@interface AxeDevToolsResultKey : NSObject
/// The name of the application that the scan came from. Should be the Bundle Identifier.
@property (nonatomic, readonly, copy) NSString * _Nonnull packageName;
/// A unique String associated with the user who pushed up the scan.  This is not the same as the username.
@property (nonatomic, readonly, copy) NSString * _Nonnull userId;
/// A unique String associated with the specific scan.
@property (nonatomic, readonly, copy) NSString * _Nonnull resultId;
@property (nonatomic, readonly) NSUInteger hash;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
/// Use this in UI Testing to convert the Floating Action Button title into a valid AxeDevToolsResultKey.  This can then be used to retrieve the scan from the server, tag it, change its name, and delete it.
/// This initializer will return <code>nil</code> if the given String is not in the expected format.  If supplying the FAB’s title directly and this method is returning <code>nil</code>, it may mean that there was an error sending the scan to the server.
/// \param fabTitle The FloatingActionButton’s <code>title</code> or <code>label</code> property after it is tapped.
///
- (nullable instancetype)initWithFabTitle:(NSString * _Nonnull)fabTitle OBJC_DESIGNATED_INITIALIZER;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Information about the device used when the scan was created.
SWIFT_CLASS("_TtC15axeDevToolsXCUI9AxeDevice")
@interface AxeDevice : NSObject
/// The name of the device
@property (nonatomic, readonly, copy) NSString * _Nonnull name;
/// The operating system that the device was running. Will likely be “iOS”.
@property (nonatomic, readonly, copy) NSString * _Nonnull os;
/// The iOS version that the device was running at the time of the scan.
@property (nonatomic, readonly, copy) NSString * _Nonnull osVersion;
/// The device’s screen height, in pixels
@property (nonatomic, readonly) float screenHeight;
/// The device’s screen width, in pixels
@property (nonatomic, readonly) float screenWidth;
/// The number of pixels in one iOS point (pt)
@property (nonatomic, readonly) float scale;
@property (nonatomic, readonly) NSUInteger hash;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@end

/// the type of object.  Derived from XCUIElement <code>ElementType</code>.
typedef SWIFT_ENUM(NSUInteger, AxeElementType, open) {
  AxeElementTypeAny = 0,
/// any view not otherwise described by the other options available in this enum.
  AxeElementTypeOther = 1,
  AxeElementTypeApplication = 2,
  AxeElementTypeWindow = 4,
  AxeElementTypeSheet = 5,
  AxeElementTypeAlert = 7,
  AxeElementTypeButton = 9,
  AxeElementTypeKeyboard = 19,
  AxeElementTypeKey = 20,
  AxeElementTypeNavigationBar = 21,
  AxeElementTypeTabBar = 22,
  AxeElementTypeTabGroup = 23,
  AxeElementTypeToolbar = 24,
  AxeElementTypeStatusBar = 25,
  AxeElementTypeTable = 26,
  AxeElementTypeCollectionView = 32,
  AxeElementTypeSlider = 33,
  AxeElementTypePageIndicator = 34,
  AxeElementTypeProgressIndicator = 35,
  AxeElementTypeActivityIndicator = 36,
  AxeElementTypeSegmentedControl = 37,
  AxeElementTypePicker = 38,
  AxeElementTypePickerWheel = 39,
  AxeElementTypeSwitch = 40,
  AxeElementTypeToggle = 41,
  AxeElementTypeLink = 42,
  AxeElementTypeImage = 43,
  AxeElementTypeSearchField = 45,
  AxeElementTypeScrollView = 46,
  AxeElementTypeScrollBar = 47,
  AxeElementTypeStaticText = 48,
  AxeElementTypeTextField = 49,
  AxeElementTypeSecureTextField = 50,
  AxeElementTypeDatePicker = 51,
  AxeElementTypeTextView = 52,
  AxeElementTypeMap = 57,
  AxeElementTypeWebView = 58,
  AxeElementTypeCell = 75,
  AxeElementTypeStepper = 79,
  AxeElementTypeTab = 80,
};


SWIFT_CLASS("_TtC15axeDevToolsXCUI8AxeFrame") SWIFT_DEPRECATED_MSG("This will be removed November 2022. Please use AxeRect (or AxeBounds) instead.")
@interface AxeFrame : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AxeFrame * _Nonnull zero;)
+ (AxeFrame * _Nonnull)zero SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly) float left;
@property (nonatomic, readonly) float right;
@property (nonatomic, readonly) float top;
@property (nonatomic, readonly) float bottom;
@property (nonatomic, readonly) float width;
@property (nonatomic, readonly) float height;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@property (nonatomic, readonly) NSUInteger hash;
- (BOOL)contains:(float)x :(float)y SWIFT_WARN_UNUSED_RESULT;
- (BOOL)containsWithFrame:(AxeFrame * _Nonnull)frame SWIFT_WARN_UNUSED_RESULT;
- (BOOL)intersects:(AxeFrame * _Nonnull)frame SWIFT_WARN_UNUSED_RESULT;
- (AxeFrame * _Nullable)intersection:(AxeFrame * _Nonnull)frame SWIFT_WARN_UNUSED_RESULT;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// A screenshot of a view, or the entire device’s screen.
SWIFT_CLASS("_TtC15axeDevToolsXCUI8AxeImage")
@interface AxeImage : NSObject
/// The screenshot, converted to base64
@property (nonatomic, readonly, copy) NSString * _Nonnull base64png;
/// The size of the image, in pixels
@property (nonatomic, readonly, strong) AxeBounds * _Nonnull frame;
@property (nonatomic, readonly) NSUInteger hash;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@end


/// How serious a failure of a rule is.
typedef SWIFT_ENUM(NSInteger, AxeImpact, open) {
/// the application is usable but has some annoyances. This is the least severe impact.
  AxeImpactMINOR = 0,
/// the application is usable but may be slightly more difficult to use for some users.
  AxeImpactMODERATE = 1,
/// the application is difficult to use for some users.
  AxeImpactSERIOUS = 2,
/// the application may not be usable or may be very difficult to use for some users.
  AxeImpactCRITICAL = 3,
/// the application is not usable for some users. This is the most severe impact.
  AxeImpactBLOCKER = 4,
};


/// The meta data of a scan.
SWIFT_CLASS("_TtC15axeDevToolsXCUI11AxeMetaData")
@interface AxeMetaData : NSObject
/// The application that was scanned
@property (nonatomic, readonly, copy) NSString * _Nonnull appIdentifier;
/// The time that the scan occurred
@property (nonatomic, readonly) int64_t analysisTimestamp;
/// The version of axeDevTools iOS used
@property (nonatomic, readonly, copy) NSString * _Nonnull axeVersion;
/// The title of the screen that was scanned, if available
@property (nonatomic, readonly, copy) NSString * _Nonnull screenTitle;
@property (nonatomic, readonly) NSUInteger hash;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// A location on the screen, either in pixels or iOS points (pt). Usually converted from a CGPoint
SWIFT_CLASS("_TtC15axeDevToolsXCUI8AxePoint")
@interface AxePoint : NSObject
/// The horizontal location of the point.
@property (nonatomic, readonly) float x;
/// The vertical location of the point.
@property (nonatomic, readonly) float y;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



/// AxeProps are all properties used to help identify views in an application and to figure out whether a view is accessible
SWIFT_CLASS("_TtC15axeDevToolsXCUI8AxeProps")
@interface AxeProps : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
/// Creates an empty AxeProps object.
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@end


@class AxeRuleResult;

/// This class contains all the information from one accessibility scan of a screen.  This is a Swift representation of the JSON sent to the axe DevTools Mobile server (if using UI automated tests or manual tests). This can be used to assert number of accessibility failures and passes on one screen.  It also contains the view hierarchy of what was scanned and which rules were run.
SWIFT_CLASS("_TtC15axeDevToolsXCUI9AxeResult")
@interface AxeResult : NSObject
/// The configuration of the scan
@property (nonatomic, readonly, strong) AxeConf * _Nonnull axeConf;
/// Information about the screen that was scanned
@property (nonatomic, readonly, strong) AxeContext * _Nonnull axeContext;
/// A list of failing, passing, ignored, and incomplete results
@property (nonatomic, readonly, copy) NSArray<AxeRuleResult *> * _Nonnull axeRuleResults;
/// All failures in the scan
@property (nonatomic, readonly, copy) NSArray<AxeRuleResult *> * _Nonnull failures;
@property (nonatomic, readonly, copy) NSArray<AxeRuleResult *> * _Nonnull violations SWIFT_DEPRECATED_MSG("This method will be removed November 2022. Please use `failures` instead");
/// All passes in the scan
@property (nonatomic, readonly, copy) NSArray<AxeRuleResult *> * _Nonnull passes;
/// All incompletes in the scan
@property (nonatomic, readonly, copy) NSArray<AxeRuleResult *> * _Nonnull incompletes;
/// A complete description of the result.  Contains summaries for each rule and prints out information about
/// any failing views.
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
/// Summary of the scan. Contains the number of failures, passes, and incompletes.
@property (nonatomic, readonly, copy) NSString * _Nonnull shortDescription;
/// Sometimes a result may be empty if it could not completely create a scan.  Use this to determine whether the result is valid.
@property (nonatomic, readonly) BOOL isEmpty SWIFT_DEPRECATED_MSG("A result can no longer be empty with the API available in 3.0, so you no longer have to check for an empty result. This method will be removed in November 2022.");
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
/// Use this after calling <code>isAccessible()</code> in your unit test to save the scan to your machine, as JSON.
/// note:
/// This function does not allow you to change the extension of the file; at this point in time it can only be saved as JSON.
/// This function will not overwrite a file if the file already exists.  Instead, it will attach a number to the end of the file name (for example, “appIdentifier-screenTitle-1.json”).
/// \param path where you want the scan to be saved to, as a String.  The path will automatically be appended to your home directory.  If not specified, the scan will save into a folder called “AttestResults” in your home directory (/Users/yourname/).
///
/// \param name What you want the file to be called, as a String. If not specified, the file’s name will be  “appIdentifier-screenTitle”.
///
///
/// returns:
/// String, the path to the saved file.
- (NSString * _Nullable)andSaveResultToPath:(NSString * _Nonnull)path withName:(NSString * _Nonnull)name SWIFT_DEPRECATED_MSG("This method will be removed November 2022. Please use AxeDevTools().saveResult instead.");
/// Use this after calling <code>isAccessible()</code> to send the scan to the server.
/// \param tags A list of tags that should be associated with the scan, as an array of String.
///
/// \param scanName A String to change the scan name too in the dashboard.
///
///
/// returns:
/// AttestResultKey, <code>nil</code> if push was not successful.
- (AttestResultKey * _Nullable)andPushResultWithTags:(NSArray<NSString *> * _Nonnull)tags withScanName:(NSString * _Nullable)scanName SWIFT_DEPRECATED_MSG("This method will be removed November 2022. Please use AxeDevTools().postResult instead.");
@end

/// The view’s primary purpose.
typedef SWIFT_ENUM(NSInteger, AxeRole, open) {
/// The view’s primary purpose is to display text. Views that can be interacted with by a user, even if they also display text, are counted as controls.
  AxeRoleTextElement = 0,
/// The view’s primary purpose is to be interacted with by the user.  Views that have text within them that are also actionable (such as buttons, textFields, etc) are counted as controls.
  AxeRoleControl = 1,
/// The view’s primary purpose is to display an image.
  AxeRoleImage = 2,
/// The view’s primary purpose is otherwise not mentioned (layout views, background views, etc).
  AxeRoleGenericElement = 3,
};

/// A unique name for each of the rules run by default.
typedef SWIFT_ENUM(NSInteger, AxeRuleId, open) {
  AxeRuleIdA11yElementFocusBox = 0,
  AxeRuleIdActiveControlName = 1,
  AxeRuleIdCollidingControls = 2,
  AxeRuleIdCollidingViews = 3,
  AxeRuleIdConflictingTraits = 4,
  AxeRuleIdFocusableText = 5,
  AxeRuleIdImageViewName = 6,
  AxeRuleIdInScrollView = 7,
  AxeRuleIdLabelAtFront = 8,
  AxeRuleIdLabelInName = 9,
  AxeRuleIdMeaningfulAccessibleName = 10,
  AxeRuleIdNestedElementsName = 11,
  AxeRuleIdTouchTargetSize = 12,
};

enum AxeStatus : NSInteger;

/// A summary of one rule being run on one view.
SWIFT_CLASS("_TtC15axeDevToolsXCUI13AxeRuleResult")
@interface AxeRuleResult : NSObject
/// whether the view passed, failed, or returned incomplete on the rule
@property (nonatomic, readonly) enum AxeStatus status;
/// refers to the end-user impact behind issues found in your scans.
/// Read more about impact in the References section of
/// axe DevTools Mobile docs at docs.deque.com.
@property (nonatomic, readonly) enum AxeImpact impact;
/// the name of the rule that was run on the view
@property (nonatomic, readonly, copy) NSString * _Nonnull ruleId;
/// a brief description of the rule that was run on the view
@property (nonatomic, readonly, copy) NSString * _Nonnull ruleSummary;
/// the properties used to determine whether the view passes or fails a rule
@property (nonatomic, readonly, strong) AxeProps * _Nonnull props;
/// the view’s identifier, calculated from its hash
/// This is identical to the AxeViewId present in AxeView
@property (nonatomic, readonly, copy) NSString * _Nonnull axeViewId;
/// whether the view is in the current screenshot.  Will be false if the view is off-screen or behind a modal.
@property (nonatomic, readonly) BOOL isVisibleToUser;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// A list of standards that the rule may fall under.
typedef SWIFT_ENUM(NSInteger, AxeStandard, open) {
/// The rule detects a failure of a WCAG 2.0 Success Criteria
  AxeStandardWCAG_20 = 0,
/// The rule detects a failure of a WCAG 2.1 Success Criteria
  AxeStandardWCAG_21 = 1,
/// The rule is a recommendation from Apple Design Guidelines
  AxeStandardPLATFORM = 2,
/// The rule is a recommendation from Deque on how to best make your app accessible.  The rule may also follow a WCAG Best Practice.
  AxeStandardBEST_PRACTICE = 3,
};

/// A set of options for when a rule is run on a view.
typedef SWIFT_ENUM(NSInteger, AxeStatus, open) {
/// The view was not applicable to the rule.
  AxeStatusINAPPLICABLE = 0,
/// The view ran into an error and needs to be reviewed for accessibility manually.
  AxeStatusINCOMPLETE = 1,
/// The view does not have an accessibility issue.
  AxeStatusPASS = 2,
/// The view has an accessibility issue.
  AxeStatusFAIL = 3,
/// The view was not checked for accessibility issues.
  AxeStatusIGNORED = 4,
};


/// The accessibility traits on a view.  Similar to UIAccessibilityTraits.
SWIFT_CLASS("_TtC15axeDevToolsXCUI9AxeTraits")
@interface AxeTraits : NSObject
@property (nonatomic) uint64_t rawValue;
@property (nonatomic, readonly) NSUInteger hash;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRawValue:(uint64_t)raw OBJC_DESIGNATED_INITIALIZER;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
- (void)formUnion:(AxeTraits * _Nonnull)other;
- (void)formIntersection:(AxeTraits * _Nonnull)other;
- (void)formSymmetricDifference:(AxeTraits * _Nonnull)other;
/// Same as UIAccessibilityTraits.adjustable
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AxeTraits * _Nonnull adjustable;)
+ (AxeTraits * _Nonnull)adjustable SWIFT_WARN_UNUSED_RESULT;
/// Same as UIAccessibilityTraits.allowsDirectInteraction
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AxeTraits * _Nonnull allowsDirectInteraction;)
+ (AxeTraits * _Nonnull)allowsDirectInteraction SWIFT_WARN_UNUSED_RESULT;
/// Same as UIAccessibilityTraits.button
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AxeTraits * _Nonnull button;)
+ (AxeTraits * _Nonnull)button SWIFT_WARN_UNUSED_RESULT;
/// Same as UIAccessibilityTraits.causesPageTurn
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AxeTraits * _Nonnull causesPageTurn;)
+ (AxeTraits * _Nonnull)causesPageTurn SWIFT_WARN_UNUSED_RESULT;
/// Same as UIAccessibilityTraits.header
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AxeTraits * _Nonnull header;)
+ (AxeTraits * _Nonnull)header SWIFT_WARN_UNUSED_RESULT;
/// Same as UIAccessibilityTraits.image
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AxeTraits * _Nonnull image;)
+ (AxeTraits * _Nonnull)image SWIFT_WARN_UNUSED_RESULT;
/// Same as UIAccessibilityTraits.keyboardKey
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AxeTraits * _Nonnull keyboardKey;)
+ (AxeTraits * _Nonnull)keyboardKey SWIFT_WARN_UNUSED_RESULT;
/// Same as UIAccessibilityTraits.link
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AxeTraits * _Nonnull link;)
+ (AxeTraits * _Nonnull)link SWIFT_WARN_UNUSED_RESULT;
/// Same as UIAccessibilityTraits.none
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AxeTraits * _Nonnull none;)
+ (AxeTraits * _Nonnull)none SWIFT_WARN_UNUSED_RESULT;
/// Same as UIAccessibilityTraits.notEnabled
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AxeTraits * _Nonnull notEnabled;)
+ (AxeTraits * _Nonnull)notEnabled SWIFT_WARN_UNUSED_RESULT;
/// Same as UIAccessibilityTraits.playsSound
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AxeTraits * _Nonnull playsSound;)
+ (AxeTraits * _Nonnull)playsSound SWIFT_WARN_UNUSED_RESULT;
/// Same as UIAccessibilityTraits.searchField
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AxeTraits * _Nonnull searchField;)
+ (AxeTraits * _Nonnull)searchField SWIFT_WARN_UNUSED_RESULT;
/// Same as UIAccessibilityTraits.selected
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AxeTraits * _Nonnull selected;)
+ (AxeTraits * _Nonnull)selected SWIFT_WARN_UNUSED_RESULT;
/// Same as UIAccessibilityTraits.startsMediaSession
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AxeTraits * _Nonnull startsMediaSession;)
+ (AxeTraits * _Nonnull)startsMediaSession SWIFT_WARN_UNUSED_RESULT;
/// Same as UIAccessibilityTraits.staticText
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AxeTraits * _Nonnull staticText;)
+ (AxeTraits * _Nonnull)staticText SWIFT_WARN_UNUSED_RESULT;
/// Same as UIAccessibilityTraits.summaryElement
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AxeTraits * _Nonnull summaryElement;)
+ (AxeTraits * _Nonnull)summaryElement SWIFT_WARN_UNUSED_RESULT;
/// Same as UIAccessibilityTraits.tabBar
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AxeTraits * _Nonnull tabBar;)
+ (AxeTraits * _Nonnull)tabBar SWIFT_WARN_UNUSED_RESULT;
/// Same as UIAccessibilityTraits.updatesFrequently
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AxeTraits * _Nonnull updatesFrequently;)
+ (AxeTraits * _Nonnull)updatesFrequently SWIFT_WARN_UNUSED_RESULT;
/// Converts an AxeTrait into an easily readable String.
///
/// returns:
/// The name of the AxeTrait. If there are multiple traits within an AxeTraits object, the traits will be in a comma-separated String.  For example, <code>(.button | .adjustable).toString()</code> would return <code>Adjustable, Button</code>.
- (NSString * _Nonnull)toString SWIFT_WARN_UNUSED_RESULT;
@end

enum RunStatus : NSInteger;
@class CalculatedProps;

/// A class representing one view in a view hierarchy.
SWIFT_CLASS("_TtC15axeDevToolsXCUI7AxeView")
@interface AxeView : NSObject
/// name of the original class, as a String (UIButton, UIWindow, DQButton, etc).
@property (nonatomic, readonly, copy) NSString * _Nonnull className;
/// the type of object.  We use this to help determine whether a rule should be run on a specific view.  AxeElementTypes are derived from XCUIElement <code>ElementType</code>.
@property (nonatomic, readonly) enum AxeElementType elementType;
/// the view’s on-screen coordinates, in pixels (not pt).
@property (nonatomic, readonly, strong) AxeBounds * _Nonnull boundsInScreen;
/// the view’s accessibility identifier.
@property (nonatomic, readonly, copy) NSString * _Nullable accessibilityIdentifier;
/// the view’s accessible name.  This is usually equivalent to the view’s accessibilityLabel or its visible text.  Will be <code>nil</code> if the view is not focusable by VoiceOver.
@property (nonatomic, readonly, copy) NSString * _Nullable name;
/// the type of the view.  See <code>AxeRole</code> for more information.
@property (nonatomic, readonly) enum AxeRole role;
/// the view’s state, if it has one.  Will be <code>nil</code> if the view is not a control.
@property (nonatomic, readonly, copy) NSString * _Nullable state;
/// the view’s value, if it has one.  Will be <code>nil</code> if the view does not have a changeable value.  Switches, sliders, steppers, etc, all have values.
@property (nonatomic, readonly, copy) NSString * _Nullable value;
/// whether a view can be directly focused by VoiceOver. This property is calculated from isAccessibilityElement, and will be false for any child views within a VoiceOver-focusable view.
@property (nonatomic, readonly) BOOL isAccessibilityFocusable;
/// whether a view can be seen on-screen at the time of the scan.  Will return false if the view is off-screen or behind a modal or other views (such as a tab bar or a navigation bar).
@property (nonatomic, readonly) BOOL isVisibleToUser;
/// The view’s subviews, as AxeViews
@property (nonatomic, readonly, copy) NSArray<AxeView *> * _Nonnull children;
/// The view’s parent, as an AxeView.
@property (nonatomic, weak) AxeView * _Nullable parent;
/// a unique identifier for the view.  The axeViewId will change between scans of the same view.
@property (nonatomic, readonly, copy) NSString * _Nonnull axeViewId;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@property (nonatomic, readonly) NSUInteger hash;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
/// Runs through the view hierarchy in a depth-first search, with the view that this method was called on as the “root” view.
/// \param function The function that should be run on the view hierarchy.
///
///
/// returns:
/// Whether to continue running through the view hierarchy.  See <code>RunStatus</code> for more information.
- (enum RunStatus)runOnSelfAndDescendants:(SWIFT_NOESCAPE enum RunStatus (^ _Nonnull)(AxeView * _Nonnull))function;
/// Finds whether the view’s provided property is true or has an ancestor whose provided property is true.
/// important:
/// <code>propName</code> must be the name of a property that is a <code>Bool</code>. If it is not, this method will log an error into the console and automatically return false.
/// \param propName a property that is a <code>Bool</code> that the view or an ancestor of the view may have set to true.
///
///
/// returns:
/// true if the view’s property is true or is a child of a view whose provided property is true; false otherwise.
- (BOOL)isPropTypeOrChildOfProp:(NSString * _Nonnull)propName SWIFT_WARN_UNUSED_RESULT;
/// Finds whether the view has an ancestor whose provided property is true.
/// important:
/// <code>propName</code> must be the name of a property that is a <code>Bool</code>. If it is not, this method will log an error into the console and automatically return false.
/// \param propName a property that is a <code>Bool</code> that an ancestor of the view may have set to true.
///
///
/// returns:
/// true if the view is a child of a view whose provided property is true; false otherwise.
- (BOOL)isChildOfProp:(NSString * _Nonnull)propName SWIFT_WARN_UNUSED_RESULT;
/// Checks whether an ancestor of this view is of the elementType provided.
/// \param elementType the type that the ancestor may be.
///
///
/// returns:
/// true if the view is a child of the elementType provided, otherwise false.
- (BOOL)isChildOfElementType:(enum AxeElementType)elementType SWIFT_WARN_UNUSED_RESULT;
/// Finds whether the view is of the elementType provided, or if the view has an ancestor that is of the elementType provided.
/// \param elementType the type that the view or an ancestor of the view may be.
///
///
/// returns:
/// true if the view is the elementType provided or if it is a child of the elementType provided; false otherwise.
- (BOOL)isElementOrChildOfElementType:(enum AxeElementType)elementType SWIFT_WARN_UNUSED_RESULT;
/// Additional properties that were calculated using the stored AxeView properties.
@property (nonatomic, readonly, strong) CalculatedProps * _Nonnull calculatedProps SWIFT_DEPRECATED_MSG("This property will be removed November 2022. Please retrieve any property using a `get` method.");
/// The type of object. We use this to help determine whether a rule should run on a specific view.
@property (nonatomic, copy) NSString * _Nonnull inheritedType SWIFT_DEPRECATED_MSG("This property will be removed November 2022. Please use `elementType` instead.");
/// the view’s frame. This property is taken directly from UIView and converted to an AxeRect.
@property (nonatomic, strong) AxeRect * _Nonnull frame SWIFT_DEPRECATED_MSG("This property will be removed November 2022. Please retrieve this property using a `get` method.");
/// the view’s text, if present.  Only available in axeDevToolsUIKit.
@property (nonatomic, copy) NSString * _Nullable text SWIFT_DEPRECATED_MSG("This property will be removed November 2022. Please retrieve this property using a `get` method.");
/// Whether the view can be activated (such as a button).
@property (nonatomic) BOOL isActiveControl SWIFT_DEPRECATED_MSG("This property will be removed November 2022. Please retrieve this property using a `get` method.");
/// Whether the view is a control and is available for interaction.
/// This property is taken directly from the <code>isEnabled</code> property present in UIControls but is converted to a String.
/// If the view is not a UIControl, this property returns <code>nil</code>.
/// If the view is a control, it returns <code>"true"</code> if <code>view.isEnabled</code> is <code>true</code> and <code>"false"</code> if <code>view.isEnabled</code> is <code>false</code>.
@property (nonatomic, copy) NSString * _Nullable isEnabled SWIFT_DEPRECATED_MSG("This property will be removed November 2022. Please retrieve this property using a `get` method.");
/// This property is taken directly from the <code>accessibilityTraits</code> property present in UIViews,
/// but is converted from <code>UIAccessibilityTraits</code> to <code>AxeTraits</code>. Do not use the
/// <code>accessibilityTraits</code> property on AxeViews, as it may be inaccurate.
@property (nonatomic, strong) AxeTraits * _Nonnull a11yTraits SWIFT_DEPRECATED_MSG("This property will be removed November 2022. Please retrieve this property using a `get` method.");
/// This property is taken directly from the <code>isAccessibilityElement</code> property present in UIViews.
/// Do not use the <code>isAccessibilityElement</code> property on AxeViews, as it may be inaccurate.  Only available in axeDevTools UIKit.
@property (nonatomic) BOOL isA11yElement SWIFT_DEPRECATED_MSG("This property will be removed November 2022. Please retrieve this property using a `get` method.");
/// This property is taken directly from the <code>accessibilityPath</code> property present in UIViews.
/// Do not use the <code>accessibilityPath</code> property on AxeViews, as it may be inaccurate.
@property (nonatomic, strong) AxeBounds * _Nullable a11yPath SWIFT_DEPRECATED_MSG("This property will be removed November 2022. Please retrieve this property using a `get` method.");
/// whether the view has an ancestor that is VoiceOver focusable.
@property (nonatomic, readonly) BOOL isInFocusableView SWIFT_DEPRECATED_MSG("This property will be removed November 2022. Please retrieve this property using the `isChildOf(ofProp)` method.");
/// whether the view has an ancestor that is a scrollView.
@property (nonatomic, readonly) BOOL isInScrollView SWIFT_DEPRECATED_MSG("This property will be removed November 2022. Please retrieve this property using the `isChild(ofElementType)` method.");
/// whether the view has an ancestor that is an active control.
@property (nonatomic, readonly) BOOL isInActiveControl SWIFT_DEPRECATED_MSG("This property will be removed November 2022. Please retrieve this property using the `isChild(ofProp)` method.");
/// whether the view has an ancestor that is a tableViewCell.
@property (nonatomic, readonly) BOOL isInTableViewCell SWIFT_DEPRECATED_MSG("This property will be removed November 2022. Please retrieve this property using the `isChild(ofElementType)` method.");
/// the view’s text and any text available on its children.
@property (nonatomic, readonly) BOOL isInCollectionViewCell SWIFT_DEPRECATED_MSG("This property will be removed November 2022. Please retrieve this property using the `isChild(ofElementType)` method.");
@property (nonatomic, readonly) BOOL hasSpeakableText SWIFT_DEPRECATED_MSG("This will be removed November 2022.");
@property (nonatomic, readonly, copy) NSString * _Nullable speakableText SWIFT_DEPRECATED_MSG("This will be removed November 2022.");
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


@interface AxeView (SWIFT_EXTENSION(axeDevToolsXCUI))
/// The text that VoiceOver reads aloud when focused on this view. Only available in axeDevTools XCUI.
@property (nonatomic, readonly, copy) NSString * _Nullable label SWIFT_DEPRECATED_MSG("This property will be removed November 2022. Please retrieve this property using a `get` method.");
@end



SWIFT_CLASS("_TtC15axeDevToolsXCUI5Props") SWIFT_DEPRECATED_MSG("This class will be removed November 2022.")
@interface Props : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@end


/// CalculatedProps are properties that can be calculated from the values given from the system.
/// All CalculatedProps need to be serialized in AxeView for use in Attest UI or in Sauron.
SWIFT_CLASS("_TtC15axeDevToolsXCUI15CalculatedProps") SWIFT_DEPRECATED_MSG("This class will be removed November 2022. Please grab properties from the AxeView directly.")
@interface CalculatedProps : Props
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, InheritedType, open) {
/// An element that is guaranteed to have text
  InheritedTypeTextElement = 0,
/// Stepper has unique properties that can cause issues with axe DevTools
  InheritedTypeStepper = 1,
/// TextField has unique properties that can cause issues with axe DevTools
  InheritedTypeTextField = 2,
/// SegmentedControl has unique properties that can cause issues with axe DevTools
  InheritedTypeSegmentedControl = 3,
/// Any other element that inherits from the UIControl class
  InheritedTypeControl = 4,
/// An image that is not nil or empty
  InheritedTypeImage = 5,
/// A scrollView
  InheritedTypeScrollView = 6,
/// A tableView cell
  InheritedTypeTableViewCell = 7,
/// A collectionView cell
  InheritedTypeCollectionViewCell = 8,
/// An element that is likely to cause false positives
  InheritedTypeIgnoredElement = 9,
/// Any other element that axe DevTools does not need to scan
  InheritedTypeGenericElement = 10,
};




/// An object that holds information about the rule, including a brief description, the severity of a failure of the rule, and whether the rule is classified as a WCAG Success Criteria.
SWIFT_CLASS("_TtC15axeDevToolsXCUI8RuleConf")
@interface RuleConf : NSObject
/// A brief description of the rule.
@property (nonatomic, readonly, copy) NSString * _Nonnull summary;
/// The standard that the rule falls under (WCAG, Best practice, etc). See <code>AxeStandard</code> for more information.
@property (nonatomic, readonly) enum AxeStandard standard;
/// The severity of a failure of the rule. See <code>AxeImpact</code> for more information.
@property (nonatomic, readonly) enum AxeImpact impact;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Whether the view hierarchy should continue to be traversed.
typedef SWIFT_ENUM(NSInteger, RunStatus, open) {
/// The view hierarchy should continue to be traversed.
  RunStatusContinue = 0,
/// The view hierarchy should no longer be traversed and will immediately stop at this point.
  RunStatusStop = 1,
/// The view hierarchy should continue to be traversed along siblings of this view and their descendants, but should not traverse through child elements of this view.
  RunStatusSkipDescendants = 2,
};

typedef SWIFT_ENUM(NSInteger, Ternary, open) {
  TernaryTrue = 0,
  TernaryFalse = 1,
  TernaryUndefined = 2,
};




#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif
