name: Notify Dependents
on:
    push:
        branches:
            - main
            - notifiy-dependents-testing

jobs:
    send-notification:
        runs-on: ubuntu-latest
        steps:

          - name: Notify Analyzer
            run: |
                echo "ohai"
                curl -X POST 'https://api.github.com/repos/dequelabs/axe-devtools-mobile-analyzer/actions/workflows/test_a_workflow.yml/dispatches' -H 'Content-Type: application/json' -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -d "{\"ref\": \"develop\"}"