name: Notify Dependents
on:
    workflow_dispatch:
    push:
        branches:
            - main
            - notify-dependents

jobs:
    send-notification:
        runs-on: ubuntu-latest
        steps:

          - name: Notify Analyzer
            run: |
                curl -X POST 'https://api.github.com/repos/dequelabs/axe-devtools-mobile-analyzer/actions/workflows/publish_latest.yml/dispatches' -H 'Content-Type: application/json' -H 'Authorization: Bearer ${{ secrets.CI_WORKFLOW_PAT }}' -d '{"ref": "main"}'
