name: Notify Dependents
on:
    push:
        branches:
            - main
            - notifiy-dependents-testing

jobs:
    send-notification:
        runs-on: ubuntu-latest
        steps:

          - name: Notify Analyzer
            run: |
                echo "ohai"